first screen layout
BagrovAnatoli/find-pair-cart-game pull request #1
Opened 2022-06-09 18:55 UTC by BagrovAnatoli

Сверстал первый экран игры

2022-06-10 09:57 UTC, mrerberg requested changes

2022-06-10 09:57 UTC, mrerberg commented on index.html
> +<html lang="en">
Сайт же на русском

2022-06-10 09:57 UTC, mrerberg commented on src/style.scss
> +        /* or 112% */
Лишний код?

2022-06-12 17:38 UTC, BagrovAnatoli commented on src/style.scss
> +        /* or 112% */
Язык поправил. В стилях немного почистил то, что не влияло на отображение.

2022-06-13 12:31 UTC, mrerberg approved these changes

2022-06-19 10:24 UTC, merged