Difficulty global state
BagrovAnatoli/find-pair-cart-game pull request #2
Opened 2022-06-15 09:41 UTC by BagrovAnatoli

Реализовал выбор уровня сложности. Он сохраняется глобально и доступен из объекта. Добавил экран игры. В зависимости от уровня, на нём разное количество карт.

2022-06-15 16:28 UTC, mrerberg requested changes

2022-06-15 16:28 UTC, mrerberg commented on index.html
> +        <!-- <div class="screen">
На всякий: мертвый код лучше не хранить. Пока это черновик, то ок

2022-06-15 16:28 UTC, mrerberg commented on index.html
> +    <script src="./src/lib/templateEngine.js"></script>
https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Modules

2022-06-15 16:28 UTC, mrerberg commented on src/img/rubashka.svg
> +<svg width="95" height="133" viewBox="0 0 95 133" fill="none" xmlns="http://www.w3.org/2000/svg">
Название файла должно быть на английском, никакого транслита

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +const appElement = document.querySelector('.app');
Я бы не рекомендовал завязывать логику на классы: классы слишком изменчивая сущность.  id/data атрибуты?

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +    time: {
Слишком абстрактное название. Время чего? Может время партии? текущей партии?

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +    time: {
И лучше хранить в общем формате (ISO, например). А уже на местах его трансформировать в то, что нужно. Это универсально

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +window.DIFFICULTY = [6,12,18];
DIFFICULTIES

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +window.DIFFICULTY = [6,12,18];
Может сделать это просто константой и импортировать в другие файлы? Так же тут не совсем сложности, а именно количество карт к сложностям. Предлагаю переделать в немного другую структуру

```js
{
  low: {
    cards: 6,
  },
  
  medium: {
     cards: 12
  },
  ...
}
```

2022-06-15 16:28 UTC, mrerberg commented on src/main.js
> +function clearElement(element) {
Это утилитарная функция, ее можно вынести из main

2022-06-15 16:28 UTC, mrerberg commented on src/timer.js
> +            const current = Date.now();
Зачем, если у тебя есть _start?

2022-06-15 16:28 UTC, mrerberg commented on src/timer.js
> +        this.secondsElement.textContent = String(window.appState.time.sec).padStart(2,0);
Форматирование времени я бы вынес в отдельную функцию/метод

2022-06-18 11:40 UTC, BagrovAnatoli commented on src/main.js
> +const appElement = document.querySelector('.app');
Привет. Ну в кривых руках любая сущность может так измениться, что мать родная не узнает)
Если серьёзно, то не очень тебя понял. За курс понятие "изменчивость" не приводилось, как что-то важное или вообще его не было. Мне проще на примерах понимать, а пока я не очень понимаю этот профессиональный язык. Что имеешь ввиду под изменчивой сущностью? Что лучше: слишком изменчивая сущность или слишком статичная? Вот такие вопросы возникают.

В этот проект я добавил класс для таймера, потому что подумал, что таймер надо будет запускать, сбрасывать, получать значения. По-моему, класс для этого хорошо подходит. Не сказал бы, что логика моего кода прям завязана на классах. Мне привычнее обычные функции, так на функциях и делаю основную логику.

2022-06-18 13:04 UTC, BagrovAnatoli commented on src/main.js
> +function clearElement(element) {
которая на 29 строке или на 31-й?
Что значит утилитарная?

2022-06-18 13:13 UTC, BagrovAnatoli commented on index.html
> +        <!-- <div class="screen">
Отсюда убрал. Но копия этой вёрстки тоже как комментарий хранится в файлах, где использую шаблонизатор. Так удобнее было его писать. Оттуда тоже лучше удалить или оставить? По-моему, так будет проще понять, какая структура описана в шаблоне.

2022-06-18 13:13 UTC, BagrovAnatoli commented on index.html
> +    <script src="./src/lib/templateEngine.js"></script>
Принял, оставлю на будущее написание с помощью модулей.

2022-06-18 13:17 UTC, BagrovAnatoli commented on src/img/rubashka.svg
> +<svg width="95" height="133" viewBox="0 0 95 133" fill="none" xmlns="http://www.w3.org/2000/svg">
Исправил.
https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/6898051c8d86bdc1a83e597a5a43c7e1c69744e3

2022-06-18 13:20 UTC, BagrovAnatoli commented on src/main.js
> +    time: {
Исправил https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/0e010e82b1746d6bfc1135690a807826ba00502c
и
https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/82d963ba4a6e04272ac1cdea345a636d28cd621e
и
https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/64424d8a27b01376bc60696f96aba3e376ee36ef

2022-06-18 13:23 UTC, BagrovAnatoli commented on src/main.js
> +window.DIFFICULTY = [6,12,18];
Поменял https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/bc6ae98571f5d882f864bb520c7b968d67ae5075

2022-06-18 13:24 UTC, BagrovAnatoli commented on src/main.js
> +window.DIFFICULTY = [6,12,18];
Сделано, (см. ответ на предыдущий комментарий) дублирую: https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2/commits/bc6ae98571f5d882f864bb520c7b968d67ae5075

2022-06-18 13:27 UTC, BagrovAnatoli commented on src/timer.js
> +            const current = Date.now();
Исправлено. 
start() зfменил на run()
_start написал так, чтобы это название не было одинаковым ы функцией, в которой оно объявлено. Замменил на startTime

2022-06-18 13:29 UTC, BagrovAnatoli commented on src/timer.js
> +        this.secondsElement.textContent = String(window.appState.time.sec).padStart(2,0);
Сделал, если правильно понял. Ссылка выше: https://github.com/BagrovAnatoli/find-pair-cart-game/pull/2#discussion_r900898732

2022-06-19 10:24 UTC, merged

2022-06-19 13:52 UTC, mrerberg commented on index.html
> +        <!-- <div class="screen">
Комментарий не самый лучший способ хранения шаблона. Это лучше сделать через код, хранить шаблон в коде. Либо с помощью тега template (в html), либо в какой-то структуре данных, с которой работает js

2022-06-19 13:54 UTC, mrerberg commented on src/main.js
> +const appElement = document.querySelector('.app');
Классы зачастую меняются. Переименовываются, дополняются, удаляются. Поэтому я и говорю, что классы изменчивы. И потом, когда удаляешь класс или изменяешь его, нужно еще убедиться, что на нем не завязана логика. Лишняя сложность. 

Css классы, я тебе не предлагаю писать на js классах. Пользуйся функциями как и делал

2022-06-19 13:56 UTC, mrerberg commented on src/main.js
> +function clearElement(element) {
Я сослался на 31 строку, значит на 31.

Утилитарная - общая, вспомогательная. Она не выполняет какую-то логику из предметной области (что-то связанное с игрой), а выполняет вспомогательную роль

2022-06-19 17:01 UTC, BagrovAnatoli commented on src/main.js
> +const appElement = document.querySelector('.app');
А, только сейчас понял, что ты про css классы. Я ещё подумал, причём тут классы(JS) и аттрибуты.

2022-06-22 10:47 UTC, BagrovAnatoli commented on index.html
> +        <!-- <div class="screen">
В коде-то это есть. Но там шаблон ввиде объекта. Он хуже читается, чем привычный html. При разработке удобно на него смотреть. Потом удалю. В курсе, который записал Александр Шлейко он так и делал. Не знаю: больше для того, чтобы нам показать как шаблон пишется, или чтобы мы в своей практике делали так-же.

2022-06-22 10:48 UTC, BagrovAnatoli commented on src/main.js
> +function clearElement(element) {
В следующем пул реквесте будет файл functions.js для таких функций.