Learn typescript
BagrovAnatoli/find-pair-cart-game pull request #5
Opened 2022-07-03 09:23 UTC by BagrovAnatoli

Адаптировал проект под typescript, добавил финальные экраны, переписал статусы как константы.

2022-07-03 14:29 UTC, mrerberg requested changes

2022-07-03 14:29 UTC, mrerberg commented on dist/index.html
> +        <!-- <link rel="stylesheet" href="./src/style.css" /> -->
Мертвый код?

2022-07-03 14:29 UTC, mrerberg commented on dist/bundle.js
> +/******/ (() => { // webpackBootstrap
dist папку нужно удалить из git и из пулл реквеста

2022-07-03 14:29 UTC, mrerberg commented on src/lib/utilityFunctions.ts
> +function takeCarts(count, set) {
Затипизируешь аргументы?

2022-07-03 14:29 UTC, mrerberg commented on src/lib/utilityFunctions.ts
> +function takeCartsForPlay(cartsCunt) {
И тут аргументы без типов

2022-07-05 07:44 UTC, BagrovAnatoli commented on src/lib/utilityFunctions.ts
> +function takeCartsForPlay(cartsCunt) {
Исправил https://github.com/BagrovAnatoli/find-pair-cart-game/pull/5/commits/0f1605cb2ed90d3ff704fbfb75237b21b02b8ab4

2022-07-05 07:44 UTC, BagrovAnatoli commented on src/lib/utilityFunctions.ts
> +function takeCarts(count, set) {
Сделал https://github.com/BagrovAnatoli/find-pair-cart-game/pull/5/commits/0f1605cb2ed90d3ff704fbfb75237b21b02b8ab4

2022-07-05 07:47 UTC, BagrovAnatoli commented on dist/index.html
> +        <!-- <link rel="stylesheet" href="./src/style.css" /> -->
Наверно, потому что не запускал npm run build, а то бы оно перезаписалось уже без этого кода. Папку dist удалил из индекса. https://github.com/BagrovAnatoli/find-pair-cart-game/pull/5

2022-07-05 07:48 UTC, BagrovAnatoli commented on dist/bundle.js
> +/******/ (() => { // webpackBootstrap
Удалил. Надеюсь, теперь нормально. https://github.com/BagrovAnatoli/find-pair-cart-game/pull/5
Но, скорее всего она в истории осталась...

2022-07-06 07:06 UTC, mrerberg approved these changes

2022-07-14 19:46 UTC, merged