Tests
BagrovAnatoli/find-pair-cart-game pull request #6
Opened 2022-07-10 14:09 UTC by BagrovAnatoli

Добавил Unit-тесты для некоторых функций, которые не работают с DOM и шаблонами.

2022-07-11 07:25 UTC, mrerberg requested changes

2022-07-11 07:25 UTC, mrerberg commented on src/timer.test.ts
> +        window.appState.gameDuration = 90000;
Тесты не должны между друг другом шарить состояние. Объяви отдельный  

```
Object.defineProperty(global, 'window'
```

для данного теста, прям внутри

2022-07-11 08:31 UTC, BagrovAnatoli commented on src/timer.test.ts
> +        window.appState.gameDuration = 90000;
https://github.com/BagrovAnatoli/find-pair-cart-game/pull/6/commits/7c3b4ed8b6db1f64f7e165523b478e27f5fc1964
Сделал. И в соседних тестах тоже

2022-07-12 06:41 UTC, mrerberg commented on src/timer.test.ts
> +        window.appState.gameDuration = 90000;
На всякий. Одно дефолтное состояние для всех тестов объявить можно, если они это состояние только читают. Ну мало ли, 4 теста одно и то же состояние используют. Но если надо переопределить состояние, делаешь отдельное состояние внутри теста и переопределяешь

2022-07-12 06:47 UTC, mrerberg requested changes

2022-07-12 06:47 UTC, mrerberg commented on src/lib/utilityFunctions.test.ts
> +    it('should length 15', () => {
А вот почему 15? Эта функция должна вроде перемешать массивы, а ко-во элементов в обоих  - 8. Почему 15?

2022-07-12 06:47 UTC, mrerberg commented on src/lib/utilityFunctions.test.ts
> +        expect(isIncludesNames).toBeTruthy();
Лучше прочекать с помощью toBe(true), так как для toBeTruthy будет валидным все, что конвертируется в true

"true", true, 1, " "

2022-07-13 07:43 UTC, BagrovAnatoli commented on src/lib/utilityFunctions.test.ts
> +    it('should length 15', () => {
![image](https://user-images.githubusercontent.com/35974249/178678102-0d9da502-a5e8-449e-83c9-78e59e6ba4f5.png)

перемножаю массивы длинами 3 и 5, получается массив из 15-и объектов.
В случае с картами не 8 и 8, а 4 и 9, которые дают 36 карт.
В данном тесте я проверяю способность функции правильно умножать, а содержимое не важно.

2022-07-14 09:37 UTC, BagrovAnatoli commented on src/lib/utilityFunctions.test.ts
> +        expect(isIncludesNames).toBeTruthy();
Заменил https://github.com/BagrovAnatoli/find-pair-cart-game/pull/6/commits/f550d5079aae34a8fc0a71b67c1092b54e2a59df

2022-07-14 09:52 UTC, mrerberg commented on src/lib/utilityFunctions.test.ts
> +    it('should length 15', () => {
Тогда у меня вопрос к названию функции. Я бы переименовал mix, потому что меня оно ввело в заблуждение

2022-07-14 11:05 UTC, BagrovAnatoli commented on src/lib/utilityFunctions.test.ts
> +    it('should length 15', () => {
Я так и подумал. Этот термин из радиоэлектроники. Миксер, смеситель - перемножают сигналы. Да, не подумал, что для большинства, это ассоциируется с другими вещами.
Заменил. https://github.com/BagrovAnatoli/find-pair-cart-game/pull/6/commits/79bdbcd81d7a5c524295d1b1474ba4ec67f649a4

2022-07-14 19:46 UTC, merged